### ISSUE TITLE
Hack throws an error

### ISSUE THREAD

**Issue by pm-nsimic** [laget-se/react-gettext-parser#2]
Im getting the following error (using CLI version):

```
node_modules/react-gettext-parser/lib/json2pot.js:30
  translations[''][''] = {
                       ^

TypeError: Cannot set property '' of undefined
    at createTranslationsTable (node_modules/react-gettext-parser/lib/json2pot.js:30:24)
    at toPot (node_modules/react-gettext-parser/lib/json2pot.js:60:39)
    at parseGlob (node_modules/react-gettext-parser/lib/parse.js:351:62)
    at Object.<anonymous> (node_modules/react-gettext-parser/lib/cli.js:33:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
```

If I uncomment the "Hack" in the line 30, everything works.

**Comment by pm-nsimic** [comment]
Update: This only happens if there are no translations to extract

**Comment by alexanderwallin** [comment]
Thanks for the feedback, @pm-nsimic!
